AWSTemplateFormatVersion: 2010-09-09
Description: Create KMS Key encrypted S3 bucket with bucket policy that denies any connections not using SSL

Parameters: 
  #  Resource parameters
  kmsStack:
    Type: String
  
  # Tag parameters
  owner:
    Type: String
    Default: sunnibunni
  ownerEmail:
    Type: String
    Default: pacheco.sunny@gmail.com
  environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - production

Resources: 
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: {'Fn::ImportValue': !Sub '${kmsStack}-kms-key'}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: owner
          Value: !Ref owner
        - Key: ownerEmail
          Value: !Ref ownerEmail
        - Key: environment
          Value: !Ref environment
        - Key: Name
          Value: !Sub ${AWS::StackName}-s3

  s3BucketPolicy0:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument: 
       Statement:
        - Effect: Deny
          Principal: '*'
          Action:
           - s3:*
          Resource:
           - !Sub 'arn:aws:s3:::${S3Bucket}'
           - !Sub 'arn:aws:s3:::${S3Bucket}/*'
          Condition:
           Bool:
            aws:SecureTransport: 'false'